version: 2
jobs:
    setup_dependencies:
        docker:
            - image: kagalpandh/kacpp-pydev
        steps:
            - checkout
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    pip3 install --user -r requirements.txt
                    # mypyはPyPIのライブラリーはPython-3.8までの型ヒント機能しか持たないため
                    # 最新版をGitから取得してインストールする必要がある。
                    python3 -m pip install -U git+git://github.com/python/mypy.git
            - save_cache:
                key: deps-{{ checksum "requirements.txt" }}
                paths:
                    - "~/.local"
    test:
        docker:
            - image: kagalpandh/kacpp-pydev
        steps:
            - checkout
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    python3 -m unittest discover -s tests -v
    thint:
        docker:
            - image: circleci/python:3.8.5
        steps:
            - checkout
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    mypy --config-file=mypy.ini SQLFileExecutor
workflows:
  version: 2
  all:
    jobs:
        - setup_dependencies
        - test:
            requires:
                - setup_dependencies
        - thint:
            requires:
                - test


